# Generated by Django 3.1 on 2021-09-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210914_1640'),
        ('cart_items', '0002_auto_20210915_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
