# Generated by Django 3.1 on 2021-09-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(db_index=True, verbose_name='Price'),
        ),
    ]
